key: :enterprise
settings:
  - key: :owner_organization_name
    default: My Organization
    aria_label: 
    description: Name of the organization that manages Marketplaces hosted on this site 
    type: string
  - key: owner_account_name
    default: admin
    description: The Enterprise owner's login account name
    type: string
namespaces:
  - key: :options
    namespaces:
      - key: :benefit_years
        settings:
          - key: :2020
            default: 0.0978
            type: :float
            description: Enter the ?? factor value for the benefit plan year